[package]
name = "httpstat-rs"
version = "0.1.0"
authors = ["Hanaasagi <ambiguous404@gmail.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4", features = ["std"] }
chrono = "0.4"
tempfile = "3"
